### PR TITLE
Adopting RFC2

### PR DESCRIPTION
**Pull request by cvvergara**
Change from "waiting for feedback" to "adopted"

### CODE REVIEW

**Comment by cvvergara** [comment]
@dkastl 
Which linter do you use?

**Comment by cvvergara** [comment]
@woodbri 
The idea is to have planned releases
The latest releases of pgRouting have being done on march and september
This RFC only covers up to pgRouting version 5 which is on september 2023.

What we want to avoid is the "dynamic" unplanned because of lack of plans it might happen again what happened from the 2.0.0 release on September 2013, the next one v2.1.0 was done on September 2015, 2 years after.

The last years since v2.1.0 up to the current one releases have being done on march and september
This RFC just makes it official whats being happening in pgRouting

**Comment by cvvergara** [comment]
The road map that we can make it can just cover up to the next major release

**Comment by dkastl** [comment]
I agree with Steve, that we may want to move the "Roadmap" to some other place. 

I like to have a yearly scheduled plan for releases rather than make this dependent on specific features. Looking at other projects it seems to work better and prevents delay. It also makes it possible to stay in sync with projects like OSGeo Live. Even if there are not many new features in a release, it gives users the feeling, that the project is active.

@cvvergara , I'm using a plugin for VisualCode, that lists possible improvements of the Markdown syntax as "Problems": https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint and https://github.com/DavidAnson/vscode-markdownlint
Not sure, how official this is. If someone knows a better one, let me know!

**Comment by cvvergara** [comment]
@dkastl @woodbri 
Can you please re-review, I made clear that that is an example, so I think

**Comment by cvvergara** [comment]
Well, now that is an example, I can make the link once the Road Map is created.
But there is no rad map yet, this is needed to create it

**Pull request merged**
